### ISSUE TITLE
where is "make_dirs" ?

### ISSUE THREAD

**Issue by insublee** [khengyeww/sym-STDP#1]
When I ran main_snn.py, i got this error.

Traceback (most recent call last):
  File "main_snn.py", line 137, in <module>
    snn.save_result()
  File "/home/insublee/sym-STDP-master/hao2019/spiking_neunet.py", line 666, in save_result
    make_dirs(self.results_path)
NameError: name 'make_dirs' is not defined

**Comment by khengyeww** [comment]
Forgot to include in import. Fixed!

**Comment by insublee** [comment]
thank you for quick response.
and also, when i ran "python main_snn.py --n_neurons 400 --batch_size 1000 --gpu" code, got this.


Training complete. (9.1071 minutes)


######################
--- Begin testing. ---
######################

!!! Testing the network with test data. !!!

  0%|                                                                                     | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main_snn.py", line 126, in <module>
    snn.test_network(n_test, data_mode='test')
  File "/home/insublee/sym-STDP-master/hao2019/spiking_neunet.py", line 411, in test_network
    inputs = {"X": batch["encoded_image"].view(self.timestep, 1, 1, 28, 28)}
RuntimeError: shape '[700, 1, 1, 28, 28]' is invalid for input of size 548800000

**Comment by khengyeww** [comment]
I'm sorry but `batch_size` training/testing is not usable at the moment as BindsNET does not provide the support needed for Hao's model to work. Even though the training process did not show any error, the training is not being done properly in actual.

I was thinking to apply a fix sometime in the future that's why I leave the `batch_size` option in the code. But for now `batch_size` can only be 1.

Sorry for the inconvenience.

**Comment by insublee** [comment]
that's so sad... thank you again.
